---
title: "A05. Managing cognitive load"
author:
- name: Martin Morgan
  affiliation: Roswell Park Comperhensive Cancer Center, Buffalo, NY
date: September 27 2018
output:
  BiocStyle::html_document:
    toc_float: true
vignette: |
  %\VignetteIndexEntry{A05. Managing cognitive load}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

'[airway][]' package.

- Himes BE, Jiang X, Wagner P, Hu R, Wang Q, Klanderman B, Whitaker
  RM, Duan Q, Lasky-Su J, Nikolos C, Jester W, Johnson M, Panettieri R
  Jr, Tantisira KG, Weiss ST, Lu Q. 'RNA-Seq Transcriptome Profiling
  Identifies CRISPLD2 as a Glucocorticoid Responsive Gene that
  Modulates Cytokine Function in Airway Smooth Muscle Cells.' PLoS
  One. 2014 Jun 13;9(6):e99625. PMID: 24926665. GEO: GSE52778.
  
[airway]: https://bioconductor.org/packages/airway
[GSE52778]: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778

```{r}
colData <- read.csv("~/extdata/rnaseq/colData.csv", row.names=1)
colData
```

```{r}
counts <- read.csv("~/extdata/rnaseq/counts.csv", row.names=1)
counts <- as.matrix(counts)
head(counts)
```

```{r}
design = ~ 0 + cell + dex
```

```{r, message=FALSE}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(counts, colData, design)
```

```{r, message=FALSE}
fit <- DESeq(dds)
results <- results(fit)
```

```{r}
head(results)
```

```{r}
results[order(results$padj),]
plot(-log10(pvalue) ~ log2FoldChange, results)
```
